baseURL = 'https://jamesishere.github.io/'
languageCode = 'en-us'
title = 'James Magee'

# URL structure: /2024/11/post-title
[permalinks]
  posts = '/:year/:month/:title/'

# Enable syntax highlighting
[markup]
  [markup.highlight]
    style = 'github'
    lineNos = false
    tabWidth = 4

# RSS configuration
[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML', 'RSS']

[params]
  description = 'Technical blog on finance, data, and systems'
  author = 'James Magee'
